# Generated by Django 5.0.2 on 2024-09-21 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_learning_prerequisite_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='learning',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.course'),
        ),
        migrations.AddField(
            model_name='learning',
            name='description',
            field=models.CharField(default='Python', max_length=20),
        ),
        migrations.AddField(
            model_name='prerequisite',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.course'),
        ),
        migrations.AddField(
            model_name='prerequisite',
            name='description',
            field=models.CharField(default='Python', max_length=20),
        ),
        migrations.AddField(
            model_name='tag',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.course'),
        ),
        migrations.AddField(
            model_name='tag',
            name='description',
            field=models.CharField(default='Python', max_length=20),
        ),
    ]
