# Generated by Django 5.0.2 on 2024-09-21 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_learning_course_learning_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learning',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.course'),
        ),
        migrations.AlterField(
            model_name='learning',
            name='description',
            field=models.CharField(default='python', max_length=20),
        ),
        migrations.AlterField(
            model_name='prerequisite',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.course'),
        ),
        migrations.AlterField(
            model_name='prerequisite',
            name='description',
            field=models.CharField(default='python', max_length=20),
        ),
        migrations.AlterField(
            model_name='tag',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.course'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='description',
            field=models.CharField(default='python', max_length=20),
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=30)),
                ('serial_number', models.IntegerField()),
                ('video_id', models.CharField(max_length=30, null=True)),
                ('is_preview', models.BooleanField(default=0)),
                ('course', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.course')),
            ],
        ),
    ]
