# Generated by Django 5.0.2 on 2024-09-21 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_learning_course_alter_learning_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='video_id',
        ),
        migrations.AddField(
            model_name='video',
            name='video_url',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='learning',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.course'),
        ),
        migrations.AlterField(
            model_name='learning',
            name='description',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='prerequisite',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.course'),
        ),
        migrations.AlterField(
            model_name='prerequisite',
            name='description',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.course'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='description',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.course'),
        ),
        migrations.AlterField(
            model_name='video',
            name='serial_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='tittle',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
